name: Deploy Next.js to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_rsa
          ${{ secrets.EC2_KEY }}
          EOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.EC2_APP_DIR }}
            
            echo "Fetching latest code..."
            git reset --hard
            git clean -fd
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Building Next.js app..."
            npm run build

            echo "Restarting application..."
            pm2 restart next-app || pm2 start npm --name "next-app"
