name: CI/CD Pipeline for Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for CI only, optional)
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            APP_DIR="$HOME/my-app"

            # Install dependencies if not present
            if ! command -v git >/dev/null; then sudo apt update && sudo apt install -y git; fi
            if ! command -v node >/dev/null; then curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt install -y nodejs; fi
            if ! command -v pm2 >/dev/null; then sudo npm install -g pm2; fi

            # Clone or update repo
            if [ ! -d "$APP_DIR/.git" ]; then
              rm -rf "$APP_DIR"
              git clone git@github.com:USERNAME/REPO.git "$APP_DIR"
            else
              cd "$APP_DIR"
              git reset --hard
              git pull origin main
            fi

            # Install project dependencies & build Next.js app
            cd "$APP_DIR"
            npm install
            npm run build

            # Restart app with pm2
            pm2 delete my-app || true
            pm2 start npm --name "my-app" -- run start
            pm2 save
          EOF
